# Generated by Django 3.1.7 on 2021-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('1', 'Аванс'), ('2', 'Продукты'), ('3', 'Хозтовары'), ('4', 'Посуда'), ('5', 'Инкассация'), ('6', 'Под отчёт'), ('7', 'Реклама'), ('8', 'Ремонтные работы'), ('9', 'Другое')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('1', 'Аванс за мероприятия'), ('2', 'Довнесение'), ('3', 'Другое')], default='1', max_length=255),
        ),
    ]
