# Generated by Django 3.1.7 on 2021-07-22 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20210715_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='added_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
